version: "3.8"

services: 
    node:
        build:
            context: .
            target: node_app_image
        container_name: node
        image: node_app:1.0
        ports: 
            - 3000:3000
        depends_on: 
            - mongo
            - redis
        environment: 
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks: 
            - node_network
    go:
        build:
            context: .
            target: go_app_image
        container_name: go
        image: go_app:1.0
        ports: 
            - 8080:8080
        depends_on: 
            - mongo
            - redis
        environment: 
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks: 
            - node_network
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        ports: 
            - 27017:27017
        networks: 
            - node_network
    redis:
        container_name: redis
        image: redis:5
        ports: 
            - 6379:6379
        networks: 
            - node_network
networks: 
    node_network:
        name: node_network

    